<a href="https://colab.research.google.com/github/Vaishujawalkar/data_analysis/blob/main/Numpy_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
np.ones(4)
np.ones((4,5))
# np.ones()#error

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#Random values
#1.randint
#np.random.randint(sv,ev,n)
arr = np.random.randint(1,10,(3))
arr1 = np.random.randint(1,10,(3,4))
arr1

array([[7, 1, 9, 1],
       [9, 6, 6, 4],
       [8, 3, 4, 8]])

In [17]:
#2. np.random.rand(n)
np.random.rand(5)#->1D
np.random.rand()#single value

0.5701461505458633

In [19]:
#3.randn
#np.random.randn(n)
np.random.randn()
np.random.randn(5)

array([-0.74909416,  0.40829969, -0.21359505, -0.0460639 ,  0.87361578])

In [27]:
#view
# var = arr_name.view()
arr = np.array([10,20,30,40])
arr1 = arr.view()
arr1
arr[0] = 800
print(arr)
print(arr1)
#addresses are different and changes are reflected

[800  20  30  40]
[800  20  30  40]


In [28]:
#copy
# var = arr_name.copy()
arr = np.array([10,20,30,40])
arr1 = arr.copy()
arr1
arr[0] = 800
print(arr)
print(arr1)
#addresses are different and changes are not reflected

[800  20  30  40]
[10 20 30 40]
